version: '{build}'
skip_tags: true
image:
  - Visual Studio 2019
configuration: Release
test: false
install:
  - ps: ./setup.ps1
build_script:
  - ps: dotnet --info
  - ps: dotnet --list-sdks
  - ps: ./build.ps1
artifacts:
- path: artifacts/Logic.Tech.Talk*.nupkg
deploy:
- provider: NuGet
  api_key:
    secure: K7lRlmBWfyD5rlXYok97X8usTb8NG3w5n5oqj8ex5QUoKma6lvUtTxEC/DfQUX90
  skip_symbols: true
  on:
    branch: /^(master|dev)$/
    CI_WINDOWS: true
- provider: GitHub
  auth_token:
    secure: o+gniYi7nDKjyJ0/uY2Fu1e2+wm9n4lFfvibGDyInJhUGfF2ykJ1KQ34FI+TOHh4
  artifact: /Logic.Tech.Talk.*\.nupkg/
  tag: v$(appveyor_build_version)
  on:
    branch: master
    CI_WINDOWS: true
