version: '{build}'
skip_tags: true
image:
  - Visual Studio 2019
configuration: Release
test: false
install:
  - ps: ./setup.ps1
build_script:
  - ps: dotnet --info
  - ps: dotnet --list-sdks
  - ps: ./build.ps1
artifacts:
- path: artifacts/Logic.Calulator.Talk*.nupkg
deploy:
- provider: NuGet
  api_key:
    secure: Z7JJQxHuGkhG15R5VCMHJ3DbZpuKt0wWRajQ6CrZIink8S+q1udHzCGCs4KdKeVp
  skip_symbols: true
  on:
    branch: /^(master|dev)$/
    CI_WINDOWS: true
- provider: GitHub
  auth_token:
    secure: 8n5mcu6F6LXbJP2bHntagZieDcdev6TQ2jmo5FxYbx4DPHWgbp0dp1Fb0zaO5YxP
  artifact: /Logic.Calulator.Talk.*\.nupkg/
  tag: v$(appveyor_build_version)
  on:
    branch: master
    CI_WINDOWS: true
